### ISSUE TITLE
Senna is missing as champion in the constants

### ISSUE THREAD

**Issue by vinzynth** [Sansossio/twisted#1]
Her ID is 235.
[champion.json](http://ddragon.leagueoflegends.com/cdn/9.22.1/data/en_US/champion.json)

**Comment by Sansossio** [comment]
Hello vinyz, feel free to add senna to constants and make a pull request!

**Comment by Sansossio** [comment]
https://github.com/Sansossio/twisted/commit/08f39d56a8d6e7235117ab54281bae3c62ec5284?diff=unified
