### ISSUE TITLE
Using start query param return Bad request - java.lang.NumberFormatException: For input string: \\"1704931200000\\"

### ISSUE THREAD

**Issue by Cuhadari-Deniz** [Sansossio/twisted#103]
After I called :

```
lolApi.MatchV5.list(puuid, RegionGroups.EUROPE, {
      start: matchMinimumDateInEpoch,
      count: 100,
      type: "ranked",
    });
```

i got this response:
```
  body: {
    status: {
      message: 'Bad request - java.lang.NumberFormatException: For input string: \\"1704931200000\\"',
      status_code: 400
    }
  }
```
  
  matchMinimumDateInEpoch:
  `const matchMinimumDateInEpoch: number = env.MATCH_MINIMUM_DATE.getTime(); // results in the number 1704931200000`
  
  As far as I can tell the LolApi Client is sending the start param as a string (wrapping it in quotation marks) therefor riots java api fails because it expected a number and not a string.

**Comment by rleaf** [comment]
Do you mean to use the `startTime` param, not `start`? In case you are, that param takes inputs in seconds not ms, so you'll have to `env.MATCH_MINIMUM_DATE.getTime() / 1000`.
