### ISSUE TITLE
BUG: League V4 Entries API should return LeagueEntryDTO[]

### ISSUE THREAD

**Issue by ziyuanmw** [Sansossio/twisted#104]
### Current
League V4 entries is parameterized to return `LeagueEntryDTO`.
https://github.com/Sansossio/twisted/blob/master/src/apis/lol/league/league.ts#L52
```
return this.request<LeagueEntryDTO>(region, endpointsV4.LeagueEntries, params, false, { page })
```

On the Riot API docs, this API returns `Set[LeagueEntryDTO]`.
https://developer.riotgames.com/apis#league-v4/GET_getLeagueEntries

### Expected
League V4 entries should be paramterized to `LeagueEntryDTO[]`.
```
return this.request<LeagueEntryDTO[]>(region, endpointsV4.LeagueEntries, params, false, { page })
```

**Comment by Sansossio** [comment]
feel free to open a pr!
