### ISSUE TITLE
[TFT] getBySummonerId

### ISSUE THREAD

**Issue by NorbertLuszkiewicz** [Sansossio/twisted#113]
Riot added new endpoint to getting summoner by `summonerId`,
and changed in data from name to `summonerId` e.g. in challenger endpoint.

Request to add this endpoint as well as endpoints related to `account_V1`

**Comment by rleaf** [comment]
Hey I'm poking around in the TFT api and am having trouble finding the issues...

> Riot added new endpoint to getting summoner by summonerId...

Could you share a link to it? I've tested [encryptedAccountId](https://developer.riotgames.com/apis#tft-summoner-v1/GET_getByAccountId), [encryptedPUUID](https://developer.riotgames.com/apis#tft-summoner-v1/GET_getByPUUID), [encryptedSummonerId](https://developer.riotgames.com/apis#tft-summoner-v1/GET_getBySummonerId) and they all work. Other than that, I'm not seeing a new endpoint added... (looking at [TFT-SUMMONER-V1](https://developer.riotgames.com/apis#tft-summoner-v1)).

> ...changed in data from name to `summonerId` e.g. in challenger endpoint.

The relevant [dto model](https://github.com/Sansossio/twisted/blob/master/src/models-dto/league/league-item/league-item.dto.ts#L22) seems to already have `summonerId`.

> Request to add ... as well as endpoints related to account_V1

Sure, can work on a pr for [get-active-shard](https://developer.riotgames.com/apis#account-v1/GET_getActiveShard)
