### ISSUE TITLE
This API does not have a page param  LEAGUE-EXP-V4 

### ISSUE THREAD

**Issue by kudzu2019** [Sansossio/twisted#114]
https://developer.riotgames.com/apis#league-exp-v4/GET_getLeagueEntries
This API does not have a page param
/**
     * Top league exp
     * @param queue Note that the queue value must be a valid ranked queue.
     * @param tier
     * @param division
     * @param region
     */
exp(queue: Queues, tier: Tiers, division: Divisions, region: Regions)

**Comment by Sansossio** [comment]
feel free to open a pr
