### ISSUE TITLE
Where to set my API Key

### ISSUE THREAD

**Issue by KastenBrot** [Sansossio/twisted#33]
Hey, I want to use your awesome package in my NodeJS Project. But I struggle setting my API Key. Where do I have to put it? 

Greeetings and thanks a lot for the Project!

**Comment by Gabb-c** [comment]
@KastenBrot 

![image](https://user-images.githubusercontent.com/65926741/98947750-5b65d880-24d4-11eb-967d-66c94d95ce43.png)

**Comment by KastenBrot** [comment]
Nice! Thanks a lot!

**Comment by Gabb-c** [comment]
Good luck with your NodeJS project :+1:
