### ISSUE TITLE
SummonerApi.getByName() does not return the same response as LeagueTFTApi.get()

### ISSUE THREAD

**Issue by olivier-deschenes** [Sansossio/twisted#39]
Hi !

So I was trying to fetch some TFT data using the account id of my summoner but I could not get a valid response. When I check the response of the **SummonerApi.getByName()**, it seems that the informations are invalid (even tho it worked well for every request like matches, masteries, ...).

### The SummonerApi.getByName() response
```
{
  id: 'MKxpgLXCfb93Jvv7Iis2ap8Nk5X3CYeYFGq_laeHCtD1E7M',
  accountId: 'A-q0x7nuFCXBurjNow-zPjEJrwGT3D8qZBtxCS6_nXayEMM',
  puuid: '7XIbpBwpihjDV6n0m3CScrd_jTl5z0mCnCc-C7QJx7HOvs8UKXPoDke1EOO5cpMfhfQ_i_quS7SeKg',
  name: 'OlivierDeschênes',
  profileIconId: 4068,
  revisionDate: 1616207435000,
  summonerLevel: 174
}
```
### The LeagueTFTApi.get() response
```
{
  id: 'EoIY9qvDwJ5dMm3k4cEl32K3ZQmsEwKvUY9TaHrhQqH6yUo',
  accountId: 'jjZPVN-v8zdpdSzPpkuSierZx8r5UcKmi9MU8GbalEJc02g',
  puuid: '4iWrr1h2u8zYo3pdAsY9c9vzpUXmU7I9Jy0J4AL6p6KXTCZ6_Q0r_GPE6Fxgrdbwvtt2kGqnPCP36Q',
  name: 'OlivierDeschênes',
  profileIconId: 4068,
  revisionDate: 1616207435000,
  summonerLevel: 174
}
```
The reponse on the RIOT  API web site return the exact same thing as your TFT api.

Do you change by any chance the data returned ? Decrypt it or something ?

Thanks !

**Comment by Sansossio** [comment]
I don't know what you mean, this library doesn't change or encrypt the information. Anyway I don't understand your problem, what is wrong with the response? It is the same than riot api website as you said

**Comment by olivier-deschenes** [comment]
The response from the TFT api is the same, but the LOL api return invalid data. The id, accountId, puuid are differant. Pretty sure they are the same for both ''games''.

**Comment by olivier-deschenes** [comment]
See the examples below.

![summoner](https://user-images.githubusercontent.com/38234745/112515936-1ea4ca80-8d6d-11eb-970d-60dc1fbb6375.png)
![TFTsummoner](https://user-images.githubusercontent.com/38234745/112515939-1f3d6100-8d6d-11eb-8a6b-97438e6d1341.png)

**Comment by Sansossio** [comment]
Are you sure that you are using the same API key for both methods on twisted? Differente API KEY mean different encrypted data by riot games, I've test twisted with lol and tft getSummonerByName and the response is the same, look:

![image](https://user-images.githubusercontent.com/15877323/112516697-d51da500-8d97-11eb-89b5-c7aeaf5d371b.png)

examples used:
https://github.com/Sansossio/twisted/blob/master/example/tft/SummonerTFT.example.ts
https://github.com/Sansossio/twisted/blob/master/example/lol/SummonerByName.example.ts

**Comment by olivier-deschenes** [comment]
Ah man that explains it, I use 2 differents key because for some reason my personnal key doesn't work with TFT data. I didn't know that they encrypted the data with **your** api key, altough it makes sense. 

Thanks.
