### ISSUE TITLE
Usage in the frontend (without Node) not possible.

### ISSUE THREAD

**Issue by CiriousJoker** [Sansossio/twisted#40]
I get that the api part of this library is made specifically for NodeJS as you're not supposed to leak your api key.

However:

- Frontend and backend have to communicate somehow
- Shared interfaces and helper functions would be helpful
- Importing Constants from the frontend throws compiler errors like `fs/process/otherdependency not found.`

Can this be fixed in any way?

**Comment by Sansossio** [comment]
Maybe importing this library through a frontend framework like react, vue or angular but I don't sure, if you find a way to do it, please update readme file.

**Comment by CiriousJoker** [comment]
It seems like this is possible, but you can only import certain parts (mainly interfaces and some constants). It's somewhat useful to share typings between frontend and backend.
