### ISSUE TITLE
Modules not found

### ISSUE THREAD

**Issue by ProgFroz** [Sansossio/twisted#5]
Hello,
I just did a fresh install and installed the library right away, meaning, there is no other library installed and nothing could affect this library in a negative way.
I get the following error when compiling though:

`ERROR in ./node_modules/twisted/dist/base/base.js
Module not found: Error: Can't resolve 'dotenv' in 'C:\Users\justi\WebstormProjects\lolweb\node_modules\twisted\dist\base'
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\justi\WebstormProjects\lolweb\node_modules\request\lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\justi\WebstormProjects\lolweb\node_modules\forever-agent'
ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\justi\WebstormProjects\lolweb\node_modules\tough-cookie\lib'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\justi\WebstormProjects\lolweb\node_modules\tunnel-agent'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\justi\WebstormProjects\lolweb\node_modules\forever-agent'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\justi\WebstormProjects\lolweb\node_modules\tunnel-agent'
`

It makes it impossible to compile unfortunately.

**Comment by Sansossio** [comment]
Can you make a minimalist version of this error? Or be free to do a pull request

**Comment by ProgFroz** [comment]
I tried so replicate, I fixed the first error by installing a bunch of different dependencies, but now I get the following:
```
Import error, can't find file:
./zlib_bindings
```
https://stackblitz.com/edit/angular-eihnmb
