### ISSUE TITLE
Any plans on adding LOL-CHALLENGES-V1?

### ISSUE THREAD

**Issue by Awolize** [Sansossio/twisted#83]
Hello! I started using the package a couple of weeks ago and it has been working great!

I was wondering if there is a plan of adding LOL-CHALLENGES-V1 to get access to the challenges. I apologize If this has been asked before. I could not find any references to it.

**Comment by Awolize** [comment]
I've made my own changes to shoehorn what I wanted from it. I can't say that all the types are 100% correct (likely not) but it does work for the 3 challenges I'm interested in. I do believe it can be a great starting point none the less. 

https://github.com/Awolize/twisted/tree/LOL-CHALLENGES-V1 

I had a hard time running the example (new genericError errors out) and ive not added any tests or examples.

**Comment by Sansossio** [comment]
feel free to open a pr!

**Comment by Awolize** [comment]
Seems like its still missing from master. What was the reason the PR was declined? #84
